version: '3.9'

services:
  topup-api-local:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    container_name: topup-api-local
    networks:
      - topupnetworks
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app

networks:
  topupnetworks:
    driver: bridge