version: '3.9'

services:
  topup-api-local:
    build:
      context: .
      dockerfile: Dockerfile.local
      target: development
    restart: always
    container_name: topup-api-local
    networks:
      - topupnetworks
    ports:
      - 3030:3000

networks:
  topupnetworks:
    driver: bridge